env:
- PROJECT_NAME=outer_join PACKAGE_NAME=main
language: cpp
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install qtbase5-dev qt5-default qttools5-dev libdbus-1-3 libxkbcommon-x11-0 xvfb gcc-7 g++-7 doxygen graphviz libgtest-dev -y
- cd /usr/src/gtest/ && sudo env "PATH=$PATH" cmake . && sudo env "PATH=$PATH" make
- sudo cp libgtest.a libgtest_main.a /usr/lib && cd -
- sudo add-apt-repository ppa:mhier/libboost-latest -y
- sudo apt-get install libboost1.70-dev -y
script:
- doxygen doxyfile.conf
- mkdir -p build
- cd build
- cmake ..
- cmake --build .
- make test
- cmake --build . --target package
- git clone https://boristestov:$GITHUB_TOKEN@github.com/boristestov/$PROJECT_NAME.github.io.git
- cd $PROJECT_NAME.github.io
- git rm -rf * || echo "Nothing to delete"
- mv -v ../../doc/html/* .
- git add .
- git commit -m "Documentation from travis-ci build $TRAVIS_BUILD_NUMBER" && git push https://boristestov:$GITHUB_TOKEN@github.com/boristestov/$PROJECT_NAME.github.io.git || echo "Nothing to commit"
- cd ..
- sudo rm -rf $PROJECT_NAME.github.io
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T $PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uboristestov:$BINTRAY_API_KEY "https://api.bintray.com/content/boristestov/$PROJECT_NAME/$PACKAGE_NAME/$TRAVIS_BUILD_NUMBER/$PROJECT_NAME-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
